In [1]:
from fdr_hacking.data_generation import *
from fdr_hacking.util import *

## simulation of data with autocorrelation

Notice that the correlation between variables in simulated data shows that the variables are correlated to the desired extent with previous variable

In [2]:
# np.random.seed(1234)
realworld_data = load_eg_realworld_data() # loading some example realworld data to have some sort of reference for parameters for beta distribution
n_observations = 200 # number of examples
n_sites = 5 # number of methylation sites
dependencies = True # whether I want dependencies or not; if false, no correlations are introduced
corr_coef_distribution = [(-0.40, -0.20), (0.70, 0.85)] # the introduced correlations will be equally represented from the specified ranges
sim_data = simulate_methyl_data(realworld_data, n_sites, n_observations, dependencies, corr_coef_distribution)
corr_sim_data = determine_correlation_matrix(sim_data)
print(corr_sim_data) # note that there is equal representation of the supplied correlation coefficient ranges and that the
# current variable is correlated with previous variable by a correlation that is specified through corr_coef_distribution

[[ 1.         -0.33175279  0.0318098   0.00901973  0.01872047]
 [-0.33175279  1.         -0.34251556 -0.299832   -0.23811895]
 [ 0.0318098  -0.34251556  1.          0.8479187   0.6121608 ]
 [ 0.00901973 -0.299832    0.8479187   1.          0.69641791]
 [ 0.01872047 -0.23811895  0.6121608   0.69641791  1.        ]]


In [3]:
n_sites = 10000 # number of methylation sites
dependencies = True # whether I want dependencies or not; if false, no correlations are introduced
# corr_coef_distribution = [(-0.79, -0.09), (-0.79, -0.09), (-0.08, 0.0), (0.0, 0.0), (0.0, 0.05),
#                           (0.06, 0.18), (0.18, 0.32), (0.18, 0.32), (0.32, 0.95), (0.32, 0.95)]
# corr_coef_distribution = [(-0.79, -0.09), (-0.08, 0.32), (0.32, 0.95)]
corr_coef_distribution = [(0.6, 0.95)]
sim_data = simulate_methyl_data(realworld_data, n_sites, n_observations, dependencies, corr_coef_distribution)
intervals = estimate_realworld_corrcoef_distribution(sim_data)
print(intervals)


[(-0.38, -0.12), (-0.12, -0.09), (-0.09, -0.07), (-0.07, -0.06), (-0.06, -0.05), (-0.05, -0.04), (-0.04, -0.03), (-0.03, -0.02), (-0.02, -0.01), (-0.01, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.01), (0.01, 0.02), (0.02, 0.03), (0.03, 0.04), (0.04, 0.05), (0.05, 0.06), (0.06, 0.07), (0.07, 0.09), (0.09, 0.12), (0.12, 0.96)]


In [ ]:
n_sites = 10000 # number of methylation sites
dependencies = True # whether I want dependencies or not; if false, no correlations are introduced
# corr_coef_distribution = [(-0.79, -0.09), (-0.79, -0.09), (-0.08, 0.0), (0.0, 0.0), (0.0, 0.05),
#                           (0.06, 0.18), (0.18, 0.32), (0.18, 0.32), (0.32, 0.95), (0.32, 0.95)]
# corr_coef_distribution = [(-0.79, -0.09), (-0.08, 0.32), (0.32, 0.95)]
corr_coef_distribution = [(0.6, 0.95)]
sim_data = simulate_methyl_data(realworld_data, n_sites, n_observations, dependencies, corr_coef_distribution)
intervals = estimate_realworld_corrcoef_distribution(sim_data)
print(intervals)


In [4]:
real_data = sample_realworld_methyl_val(n_sites=n_sites, realworld_data=realworld_data)
real_intervals = estimate_realworld_corrcoef_distribution(sim_data)
print(real_intervals)


[(-0.38, -0.12), (-0.12, -0.09), (-0.09, -0.07), (-0.07, -0.06), (-0.06, -0.05), (-0.05, -0.04), (-0.04, -0.03), (-0.03, -0.02), (-0.02, -0.01), (-0.01, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.01), (0.01, 0.02), (0.02, 0.03), (0.03, 0.04), (0.04, 0.05), (0.05, 0.06), (0.06, 0.07), (0.07, 0.09), (0.09, 0.12), (0.12, 0.96)]
